### ISSUE TITLE
daemon fails to start -- findCaller() TypeError

### ISSUE THREAD

**Issue by austin-millan** [binhex/arch-delugevpn#140]
I recently rebuilt delugevpn in my Unraid environment and ran into issues with starting. Here's the setup:

**Docker-Compose version:** 1.24.1, build 4667896b
**binhex/arch-delugevpn version:** latest

**docker-compose file:**
```
version: '3.3'
networks:
  frontend:
    ipam:
      config:
        - subnet: 192.168.0.0/24
volumes:
  caddy:
services:
  arch-delugevpn:
    image: binhex/arch-delugevpn
    container_name: binhex-delugevpn-dc
    restart: always
    privileged: true
    networks:
      frontend:
        ipv4_address: 192.168.0.2
    ports:
      - '8112:8112/tcp'
      - '58846:58846/tcp'
      - '58946:58946/tcp'
      - '58946:58946/udp'
      - '8118:8118/tcp'
    volumes:
      - '/mnt/user/downloads/:/data:rw'
      - '/mnt/user/appdata/binhex-delugevpn3:/config:rw'
    logging:
      options:
        max-size: 1g
    environment:
      - TZ=<REDACTED>
      - HOST_OS=<REDACTED>
      - VPN_ENABLED=yes
      - "VPN_USER=<REDACTED>"
      - "VPN_PASS=<REDACTED>"
      - VPN_PROV=pia
      - VPN_OPTIONS=
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=<REDACTED>
      - "NAME_SERVERS=<REDACTED>"
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=debug
      - DEBUG=true
      - UMASK=000
      - PUID=0
      - PGID=0
```

The container logs shows a lot of unhandled Python exceptions:

```log
binhex-delugevpn-dc | 2019-11-18T22:25:15.362474669Z 2019-11-18 14:25:15,362 DEBG 'watchdog-script' stdout output:
binhex-delugevpn-dc | 2019-11-18T22:25:15.362501193Z [info] Deluge process started
binhex-delugevpn-dc | 2019-11-18T22:25:15.362507883Z [info] Waiting for Deluge process to start listening on port 58846...
binhex-delugevpn-dc | 2019-11-18T22:25:15.362512815Z 
binhex-delugevpn-dc | 2019-11-18T22:25:15.468747765Z 2019-11-18 14:25:15,468 DEBG 'watchdog-script' stderr output:
binhex-delugevpn-dc | 2019-11-18T22:25:15.468795595Z Unhandled error in Deferred:
binhex-delugevpn-dc | 2019-11-18T22:25:15.468802585Z 
binhex-delugevpn-dc | 2019-11-18T22:25:15.469722752Z 2019-11-18 14:25:15,469 DEBG 'watchdog-script' stderr output:
binhex-delugevpn-dc | 2019-11-18T22:25:15.469734453Z 
binhex-delugevpn-dc | 2019-11-18T22:25:15.469740176Z Traceback (most recent call last):
binhex-delugevpn-dc | 2019-11-18T22:25:15.469745210Z   File "/usr/lib/python3.8/site-packages/deluge/core/daemon_entry.py", line 112, in run_daemon
binhex-delugevpn-dc | 2019-11-18T22:25:15.469750592Z     daemon = Daemon(
binhex-delugevpn-dc | 2019-11-18T22:25:15.469755222Z   File "/usr/lib/python3.8/site-packages/deluge/core/daemon.py", line 94, in __init__
binhex-delugevpn-dc | 2019-11-18T22:25:15.469759735Z     log.info('Deluge daemon %s', get_version())
binhex-delugevpn-dc | 2019-11-18T22:25:15.469764512Z   File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
binhex-delugevpn-dc | 2019-11-18T22:25:15.469769016Z     return _cancellableInlineCallbacks(gen)
binhex-delugevpn-dc | 2019-11-18T22:25:15.469773120Z   File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
binhex-delugevpn-dc | 2019-11-18T22:25:15.469777774Z     _inlineCallbacks(None, g, status)
binhex-delugevpn-dc | 2019-11-18T22:25:15.469781933Z --- <exception caught here> ---
binhex-delugevpn-dc | 2019-11-18T22:25:15.469797619Z   File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
binhex-delugevpn-dc | 2019-11-18T22:25:15.469803265Z     result = g.send(result)
binhex-delugevpn-dc | 2019-11-18T22:25:15.469807631Z   File "/usr/lib/python3.8/site-packages/deluge/log.py", line 69, in info
binhex-delugevpn-dc | 2019-11-18T22:25:15.469812461Z     yield LoggingLoggerClass.info(self, msg, *args, **kwargs)
binhex-delugevpn-dc | 2019-11-18T22:25:15.469817067Z   File "/usr/lib/python3.8/logging/__init__.py", line 1434, in info
binhex-delugevpn-dc | 2019-11-18T22:25:15.469821797Z     self._log(INFO, msg, args, **kwargs)
binhex-delugevpn-dc | 2019-11-18T22:25:15.469826199Z   File "/usr/lib/python3.8/logging/__init__.py", line 1565, in _log
binhex-delugevpn-dc | 2019-11-18T22:25:15.469830857Z     fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
binhex-delugevpn-dc | 2019-11-18T22:25:15.469835391Z builtins.TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
binhex-delugevpn-dc | 2019-11-18T22:25:15.469839951Z 
binhex-delugevpn-dc | 2019-11-18T22:25:15.469844098Z 
binhex-delugevpn-dc | 2019-11-18T22:25:15.470540088Z 2019-11-18 14:25:15,470 DEBG 'watchdog-script' stderr output:
binhex-delugevpn-dc | 2019-11-18T22:25:15.470555250Z Temporarily disabling observer LegacyLogObserverWrapper(<bound method TwistedLoggingObserver.emit of <deluge.log.TwistedLoggingObserver object at 0x149014942940>>) due to exception: [Failure instance: Traceback: <class 'TypeError'>: findCaller() takes from 1 to 2 positional arguments but 3 were given
binhex-delugevpn-dc | 2019-11-18T22:25:15.470560258Z /usr/lib/python3.8/site-packages/pkg_resources/__init__.py:2074:dist_factory
binhex-delugevpn-dc | 2019-11-18T22:25:15.470563355Z /usr/lib/python3.8/site-packages/twisted/internet/defer.py:962:__del__
binhex-delugevpn-dc | 2019-11-18T22:25:15.470566408Z /usr/lib/python3.8/site-packages/twisted/logger/_logger.py:190:failure
binhex-delugevpn-dc | 2019-11-18T22:25:15.470570301Z /usr/lib/python3.8/site-packages/twisted/logger/_logger.py:144:emit
binhex-delugevpn-dc | 2019-11-18T22:25:15.470574933Z --- <exception caught here> ---
binhex-delugevpn-dc | 2019-11-18T22:25:15.470579717Z /usr/lib/python3.8/site-packages/twisted/logger/_observer.py:131:__call__
binhex-delugevpn-dc | 2019-11-18T22:25:15.470584396Z /usr/lib/python3.8/site-packages/twisted/logger/_legacy.py:93:__call__
binhex-delugevpn-dc | 2019-11-18T22:25:15.470589154Z /usr/lib/python3.8/site-packages/deluge/log.py:204:emit
binhex-delugevpn-dc | 2019-11-18T22:25:15.470593734Z /usr/lib/python3.8/logging/__init__.py:1481:critical
binhex-delugevpn-dc | 2019-11-18T22:25:15.470598349Z /usr/lib/python3.8/logging/__init__.py:1565:_log
binhex-delugevpn-dc | 2019-11-18T22:25:15.470602892Z ]
binhex-delugevpn-dc | 2019-11-18T22:25:15.470607547Z Traceback (most recent call last):
binhex-delugevpn-dc | 2019-11-18T22:25:15.470612139Z   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2074, in dist_factory
binhex-delugevpn-dc | 2019-11-18T22:25:15.470617407Z     is_meta = any(map(lower.endswith, ('.egg-info', '.dist-info')))
binhex-delugevpn-dc | 2019-11-18T22:25:15.470622385Z   File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 962, in __del__
binhex-delugevpn-dc | 2019-11-18T22:25:15.470627492Z     log.failure(format,
binhex-delugevpn-dc | 2019-11-18T22:25:15.470632356Z   File "/usr/lib/python3.8/site-packages/twisted/logger/_logger.py", line 190, in failure
binhex-delugevpn-dc | 2019-11-18T22:25:15.470647508Z     self.emit(level, format, log_failure=failure, **kwargs)
binhex-delugevpn-dc | 2019-11-18T22:25:15.470653430Z   File "/usr/lib/python3.8/site-packages/twisted/logger/_logger.py", line 144, in emit
binhex-delugevpn-dc | 2019-11-18T22:25:15.470658817Z     self.observer(event)
binhex-delugevpn-dc | 2019-11-18T22:25:15.470663654Z --- <exception caught here> ---
binhex-delugevpn-dc | 2019-11-18T22:25:15.470668772Z   File "/usr/lib/python3.8/site-packages/twisted/logger/_observer.py", line 131, in __call__
binhex-delugevpn-dc | 2019-11-18T22:25:15.470674050Z     observer(event)
binhex-delugevpn-dc | 2019-11-18T22:25:15.470678886Z   File "/usr/lib/python3.8/site-packages/twisted/logger/_legacy.py", line 93, in __call__
binhex-delugevpn-dc | 2019-11-18T22:25:15.470684030Z     self.legacyObserver(event)
binhex-delugevpn-dc | 2019-11-18T22:25:15.470688910Z   File "/usr/lib/python3.8/site-packages/deluge/log.py", line 204, in emit
binhex-delugevpn-dc | 2019-11-18T22:25:15.470694019Z     getattr(LoggingLoggerClass, event_dict['log_level'].name)(
binhex-delugevpn-dc | 2019-11-18T22:25:15.470699059Z   File "/usr/lib/python3.8/logging/__init__.py", line 1481, in critical
binhex-delugevpn-dc | 2019-11-18T22:25:15.470705027Z     self._log(CRITICAL, msg, args, **kwargs)
binhex-delugevpn-dc | 2019-11-18T22:25:15.470710143Z   File "/usr/lib/python3.8/logging/__init__.py", line 1565, in _log
binhex-delugevpn-dc | 2019-11-18T22:25:15.470715293Z     fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
binhex-delugevpn-dc | 2019-11-18T22:25:15.470720157Z builtins.TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
........
```

Something to note is this may be a versioning issue [`python-twisted`](https://pypi.org/project/Twisted/), as Twisted seems to only support up to (inclusive) Python 3.7, while the only interpreter in the container's path is: Python 3.8.0.

I have tried using an older `arch-delugevpn` image, and I get this same error every time, even dating back 3 months. 

Edit: Everything else seems to be fine besides this error

**Comment by dennisboris** [comment]
I'm having the same problem with the same error message after reinstalling my server. I'm running the latest docker with Ubuntu Server 18.04.

**Comment by austin-millan** [comment]
Just wanted to point out that this error doesn't seem to impact performance or security, traffic seems to be coming from my VPN and the container isn't using RAM / CPU in any remarkable ways.

The one thing that doesn't seem to be working is external plugins for Deluge. I'm unable to successfully complete any Egg installations.

**Comment by binhex** [comment]
this is a python 3.8 incompatibility that it being worked through, the latest image now fixes this particular issue.
