### ISSUE TITLE
Please add python-requests package for AutoRemovePlus

### ISSUE THREAD

**Issue by staticn0de** [binhex/arch-delugevpn#148]
Would you please also add python-requests package to this container for AutoRemovePlus. Adding the python future package has the following error:

`Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
  File "/config/plugins/AutoRemovePlus-0.6.8-py3.8.egg/autoremoveplus/__init__.py", line 48, in __init__
    from autoremoveplus.core import Core as _plugin_cls
  File "<frozen zipimport>", line 259, in load_module
  File "/config/plugins/AutoRemovePlus-0.6.8-py3.8.egg/autoremoveplus/core.py", line 51, in <module>
    from .mediaserver import Mediaserver
  File "<frozen zipimport>", line 259, in load_module
  File "/config/plugins/AutoRemovePlus-0.6.8-py3.8.egg/autoremoveplus/mediaserver.py", line 24, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

Manually installing python-requests within the container allows the plugin to start and function as expected.

`pacman -S --needed python-requests --noconfirm`

`06:09:59.681 [INFO    ][deluge.pluginmanagerbase      :69  ] Plugin AutoRemovePlus enabled...`

Ref: https://github.com/binhex/arch-delugevpn/issues/147

python-future and python-requests will also be needed in:
https://github.com/binhex/arch-deluge/issues/7

**Comment by binhex** [comment]
done.

**Comment by maxwell-01** [comment]
Just wanted to say thank you for this!

**Comment by fun4stuff** [comment]
How do install auto remove plus? Doesn’t seem to work through the “install” under plugins section in preference.

**Comment by maxwell-01** [comment]
Read the instructions for the plugin - add the egg to the plugins folder
within deluge config.
