### ISSUE TITLE
watchdog script stderror

### ISSUE THREAD

**Issue by snugglej** [binhex/arch-delugevpn#151]
Hello,

I just pulled the latest version of your container from docker and I'm getting an error in the watchdog script. Everything seems to be working fine for the deluge and openvpn setup. 

Here is what my log looks like from the startup and running of the container. Let me know what I probably did wrong but I don't believe I was having this issue prior to the upgrade to the latest container.

>2019-12-20 04:41:09,391 DEBG 'watchdog-script' stderr output:,
Unable to initialize gettext/locale!,
,
2019-12-20 04:41:09,391 DEBG 'watchdog-script' stderr output:,
'ngettext',
Traceback (most recent call last):,
  File "/usr/lib/python3.8/site-packages/deluge/i18n/util.py", line 118, in setup_translation,
    builtins.__dict__['_n'] = builtins.__dict__['ngettext'],
KeyError: 'ngettext',
,
2019-12-20 04:41:12,662 DEBG 'watchdog-script' stdout output:,
Setting "random_port" to: False,
Configuration value successfully updated.,
,
2019-12-20 04:41:13,005 DEBG 'watchdog-script' stderr output:,
Unable to initialize gettext/locale!,
,
2019-12-20 04:41:13,006 DEBG 'watchdog-script' stderr output:,
'ngettext',
Traceback (most recent call last):,
  File "/usr/lib/python3.8/site-packages/deluge/i18n/util.py", line 118, in setup_translation,
    builtins.__dict__['_n'] = builtins.__dict__['ngettext'],
KeyError: 'ngettext',
,
2019-12-20 04:41:16,267 DEBG 'watchdog-script' stdout output:,
Setting "listen_ports" to: (53929, 53929),
Configuration value successfully updated.,
,
2019-12-20 04:41:16,634 DEBG 'watchdog-script' stderr output:,
Unable to initialize gettext/locale!,
,
2019-12-20 04:41:16,634 DEBG 'watchdog-script' stderr output:,
'ngettext',
Traceback (most recent call last):,
  File "/usr/lib/python3.8/site-packages/deluge/i18n/util.py", line 118, in setup_translation,
    builtins.__dict__['_n'] = builtins.__dict__['ngettext'],
KeyError: 'ngettext',
,
2019-12-20 04:41:20,137 DEBG 'watchdog-script' stdout output:,
[info] No torrents with state 'Error' found,
,
2019-12-20 04:41:20,137 DEBG 'watchdog-script' stdout output:,
[info] Starting Deluge Web UI...,
,
2019-12-20 04:41:20,138 DEBG 'watchdog-script' stdout output:,
[info] Deluge Web UI started,
,
2019-12-20 04:41:20,435 DEBG 'watchdog-script' stderr output:,
Unable to initialize gettext/locale!,
,
2019-12-20 04:41:20,435 DEBG 'watchdog-script' stderr output:,
'ngettext',
Traceback (most recent call last):,
  File "/usr/lib/python3.8/site-packages/deluge/i18n/util.py", line 118, in setup_translation,
    builtins.__dict__['_n'] = builtins.__dict__['ngettext'],
KeyError: 'ngettext',
,

**Comment by Pannkaaka** [comment]
I get the same errors running the latest version.

**Comment by jjbrunton** [comment]
Also have this issue on the latest tag

**Comment by devanl** [comment]
+1

**Comment by binhex** [comment]
As far as I know this is a minor issue with no real repercussions (correct me if I'm wrong) and is caused by the update to python 3.8, in time I expect this to be fixed upstream

**Comment by snugglej** [comment]
@binhex I agree it is minor and that is fine that it would get fixed upstream. It is still an issue since it throws a warning. I'm fine with it being there because it causes no real I'll effects. 

Is there already an upstream bug for this?

**Comment by JustinGrote** [comment]
I don't know if this is related but my container won't download anything thru OpenVPN-PrivateInternetAccess if I see this error. The earliest container I don't see the issue anymore is 2.0.3-1-08. I ran a default config and had the same issue, so it definitely seems to have been introduced in 2.0.3-2-01.

**Comment by binhex** [comment]
Nothing too do with this issue, please raise a separate issue
