### ISSUE TITLE
unable to initialize gettext/locale error

### ISSUE THREAD

**Issue by adstep** [binhex/arch-delugevpn#161]
Having some trouble when starting up the container.

```
[info] Deluge process started
[info] Waiting for Deluge process to start listening on port 58846...
2020-02-12 01:09:53,239 DEBG 'watchdog-script' stdout output:
[info] Deluge process listening on port 58846
2020-02-12 01:09:53,543 DEBG 'watchdog-script' stderr output:
Unable to initialize gettext/locale!
2020-02-12 01:09:53,543 DEBG 'watchdog-script' stderr output:
'ngettext'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deluge/i18n/util.py", line 118, in setup_translation
    builtins.__dict__['_n'] = builtins.__dict__['ngettext']
KeyError: 'ngettext'
2020-02-12 01:09:55,930 DEBG 'watchdog-script' stdout output:
[info] No torrents with state 'Error' found
2020-02-12 01:09:55,930 DEBG 'watchdog-script' stdout output:
[info] Starting Deluge Web UI...
2020-02-12 01:09:55,930 DEBG 'watchdog-script' stdout output:
[info] Deluge Web UI started
2020-02-12 01:09:56,225 DEBG 'watchdog-script' stderr output:
Unable to initialize gettext/locale!
2020-02-12 01:09:56,225 DEBG 'watchdog-script' stderr output:
'ngettext'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deluge/i18n/util.py", line 118, in setup_translation
    builtins.__dict__['_n'] = builtins.__dict__['ngettext']
KeyError: 'ngettext'
```

**Comment by adstep** [comment]
This [issue](https://bbs.archlinux.org/viewtopic.php?id=252811) might be related. Seems to have been reported just recently.

**Comment by binhex** [comment]
its a cosmetic issue at this point and will be fixed up stream by deluge devs at some point in the future.
