### ISSUE TITLE
Deluge not starting anymore ('watchdog-script' stderr output)

### ISSUE THREAD

**Issue by tommyvange** [binhex/arch-delugevpn#184]
My Deluge (binhex/arch-delugevpn) docker container is no longer starting. It is throwing the following error code:
```
2020-05-28 01:35:57,389 DEBG 'watchdog-script' stderr output:
Unhandled error in Deferred:


2020-05-28 01:35:57,393 DEBG 'watchdog-script' stderr output:

Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 1283, in run
self.mainLoop()
File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 1292, in mainLoop
self.runUntilCurrent()
File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
call.func(*call.args, **call.kw)
File "/usr/lib/python3.8/site-packages/twisted/internet/task.py", line 239, in __call__
d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
result = f(*args, **kw)
File "/usr/lib/python3.8/site-packages/deluge/core/alertmanager.py", line 70, in update
self.handle_alerts()
File "/usr/lib/python3.8/site-packages/deluge/core/alertmanager.py", line 138, in handle_alerts
**{
File "/usr/lib/python3.8/site-packages/deluge/core/alertmanager.py", line 139, in <dictcomp>
attr: getattr(alert, attr)
builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 34: invalid continuation byte
```
I have no idea as to what caused the issue as I did not make any changes to the container or deluge settings. The only thing i did was add a lot of torrents (~200). 

What happened was that I was looking at the progress of the torrents and then i suddenly got the _Disconnected_ error message, and then the web server never went back online. If it was just the web server it would have been fine but the error is preventing the whole client from starting which is a huge problem.

I have already started to get hit and runs on multiple torrent sites, so it would be great if i could get this fixed before my account gets banned from the sites.

Solutions I have tried:
 - Restarting the container
 - Re-installing the container
 - Disabling the VPN
 - Disabling _Strict Port-forwarding_
 - Downgrading the Docker Image
 - Re-Installing the Docker Image

Nothing is working, please help me as I really don't want to get banned from all my torrent sites.

I am running Docker 19.03.5 on UnRaid 6.8.3.

**Comment by tommyvange** [comment]
**Update**
When i woke up this morning deluge was running again, so i guess i was just impatient?

Anyways, closing this issue as I no longer need help.
