### ISSUE TITLE
Deluge failing due to missing python imports

### ISSUE THREAD

**Issue by kopf** [binhex/arch-delugevpn#236]
Hi,

I've suddenly started having problems with my `arch-delugevpn` container. I figured this is most likely due to an upgrade to the latest tag, however when I downgrade to `2.0.4.dev38_g23a48dd01-2-15` (pushed about a month ago), the problems persist. 

In the logs, I'm seeing:

```
2020-12-06 13:19:02,336 DEBG 'watchdog-script' stdout output:
[info] Attempting to start Deluge...
[info] Removing deluge pid file (if it exists)...

2020-12-06 13:19:02,380 DEBG 'watchdog-script' stderr output:
Traceback (most recent call last):
  File "/home/nobody/config_deluge.py", line 13, in <module>
    from deluge.config import Config
ModuleNotFoundError: No module named 'deluge.config'

2020-12-06 13:19:02,426 DEBG 'watchdog-script' stderr output:
Traceback (most recent call last):
  File "/home/nobody/config_deluge.py", line 13, in <module>
    from deluge.config import Config
ModuleNotFoundError: No module named 'deluge.config'

2020-12-06 13:19:02,482 DEBG 'watchdog-script' stderr output:
Traceback (most recent call last):
  File "/home/nobody/config_deluge.py", line 13, in <module>
    from deluge.config import Config
ModuleNotFoundError: No module named 'deluge.config'

2020-12-06 13:19:02,543 DEBG 'watchdog-script' stderr output:
Traceback (most recent call last):
  File "/usr/bin/deluged", line 33, in <module>
    sys.exit(load_entry_point('deluge==2.0.4.dev38', 'console_scripts', 'deluged')())
  File "/usr/bin/deluged", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deluge.core.daemon_entry'

2020-12-06 13:19:13,682 DEBG 'watchdog-script' stdout output:
[warn] Wait for Deluge process to start aborted, too many retries
[info] Showing output from command before exit...

2020-12-06 13:19:13,740 DEBG 'watchdog-script' stderr output:
Traceback (most recent call last):
  File "/usr/bin/deluged", line 33, in <module>
    sys.exit(load_entry_point('deluge==2.0.4.dev38', 'console_scripts', 'deluged')())
  File "/usr/bin/deluged", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deluge.core.daemon_entry'
```

The application seems to start up (it logs to the console) but the WebUI isn't responding. Running `deluge-console` inside the container results in:

```
[root@6d94ed259c45 /]# deluge-console
Traceback (most recent call last):
  File "/usr/sbin/deluge-console", line 33, in <module>
    sys.exit(load_entry_point('deluge==2.0.4.dev38', 'console_scripts', 'deluge-console')())
  File "/usr/sbin/deluge-console", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'deluge.ui.console' has no attribute 'start'
[root@6d94ed259c45 /]#
```

**Comment by kopf** [comment]
Apologies, I'd had old versions of plugins mounted as volumes inside the container. 

My own mistake.
