### ISSUE TITLE
Cannot Start Deluge - stderr output

### ISSUE THREAD

**Issue by negativzeroe** [binhex/arch-delugevpn#244]
I saw one issue opened for this but the user closed it as it resolved itself the next day. I've had this issue for about three days now trying to completely remove the containers and volumes, redownloading, etc. I have two containers running in parallel, which I've done all year, and am only getting this in one of them. 

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python3.8/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python3.8/site-packages/deluge/core/alertmanager.py", line 70, in update
    self.handle_alerts()
  File "/usr/lib/python3.8/site-packages/deluge/core/alertmanager.py", line 138, in handle_alerts
    **{
  File "/usr/lib/python3.8/site-packages/deluge/core/alertmanager.py", line 139, in <dictcomp>
    attr: getattr(alert, attr)
builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 0: invalid continuation byte
```

**Comment by negativzeroe** [comment]
This is still an issue by the way, I have to restart the container like every five minutes.

**Comment by wranglatang** [comment]
@negativzeroe Was there ever a solution to this? im getting it all the time now even after having deluge running no problem for about 2 years!!

**Comment by negativzeroe** [comment]
> @negativzeroe Was there ever a solution to this? im getting it all the time now even after having deluge running no problem for about 2 years!!

Not really a fix but I've found if you go into config/state, and remove all of that it will restart. You can also move them elsewhere and try re uploading.

**Comment by wranglatang** [comment]
Thanks, where are you looking for "config / state"?

**Comment by wranglatang** [comment]
ah right, i found it in the files. that gets rid of all the current downloads right? then i need to do a fresh load of the torrents?
