### ISSUE TITLE
Unable to open torrent files

### ISSUE THREAD

**Issue by Subbeh** [binhex/arch-delugevpn#319]
Nothing happens in the web GUI when I open either a torrent file or a magnet link.

Looking at the `deluge-web.log` logs, there seem to be a lot of the following errors happening constantly:

```
20:34:40 [DEBUG   ][deluge.ui.client           :170 ] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: core.get_session_status(['peer.num_peers_connected', 'payload_download_rate', 'payload_upload_rate', 'download_rate', 'upload_rate', 'dht.dht_nodes', 'net.has_incoming_connections'])
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/deluge/core/rpcserver.py", line 330, in dispatch
    raise NotAuthorizedError(auth_level, method_auth_requirement)
deluge.error.NotAuthorizedError: Auth level too low: 0 < 5

NotAuthorizedError: Auth level too low: 0 < 5
```
Once the torrent is added, this appears in the logfile:

```
20:34:41 [DEBUG   ][deluge.ui.web.json_api     :199 ] json-request: b'{"method":"web.add_torrents","params":[[{"path":"/tmp/delugeweb-rr0qr76a/ubuntu-22.04-desktop-amd64.iso.torrent","options":{}}]],"id":171}'
20:34:41 [INFO    ][deluge.ui.web.json_api     :733 ] Adding torrent from file `ubuntu-22.04-desktop-amd64.iso.torrent` with options `{}`
20:34:41 [DEBUG   ][deluge.ui.client           :170 ] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: core.add_torrent_file_async(ubuntu-22.04-desktop-amd64.iso.torrent,
< ... a lot of gibberish ... > 
    raise NotAuthorizedError(auth_level, method_auth_requirement)
deluge.error.NotAuthorizedError: Auth level too low: 0 < 5

NotAuthorizedError: Auth level too low: 0 < 5
--------------------------------------------------------------------------------
20:34:41 [ERROR   ][deluge.ui.web.json_api     :182 ] [Failure instance: Traceback: <class 'TypeError'>: Object of type Failure is not JSON serializable
/usr/lib/python3.10/site-packages/twisted/internet/defer.py:858:_runCallbacks
/usr/lib/python3.10/site-packages/twisted/internet/defer.py:1338:_cbDeferred
/usr/lib/python3.10/site-packages/twisted/internet/defer.py:662:callback
/usr/lib/python3.10/site-packages/twisted/internet/defer.py:764:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python3.10/site-packages/twisted/internet/defer.py:858:_runCallbacks
/usr/lib/python3.10/site-packages/deluge/ui/web/json_api.py:176:_on_rpc_request_finished
/usr/lib/python3.10/site-packages/deluge/ui/web/json_api.py:229:_send_response
/usr/lib/python3.10/json/__init__.py:231:dumps
/usr/lib/python3.10/json/encoder.py:199:encode
/usr/lib/python3.10/json/encoder.py:257:iterencode
/usr/lib/python3.10/json/encoder.py:179:default
]
20:34:42 [DEBUG   ][deluge.ui.web.json_api     :199 ] json-request: b'{"method":"web.update_ui","params":[["queue","name","total_wanted","state","progress","num_seeds","total_seeds","num_peers","total_peers","download_payload_rate","upload_payload_rate","eta","ratio","distributed_copies","is_auto_managed","time_added","tracker_host","download_location","last_seen_complete","total_done","total_uploaded","max_download_speed","max_upload_speed","seeds_peers_ratio","total_remaining","completed_time","time_since_transfer"],{}],"id":172}'
20:34:42 [DEBUG   ][deluge.ui.client           :170 ] RPCError Message Received!
```

**Comment by Subbeh** [comment]
Instead of the latest release, I tried version 2.0.5-1-04 and that works fine.

**Comment by nabeelshaikh7** [comment]
i tried it and it still doesn't work

`torr  | 2022-08-06 18:48:26,378 DEBG 'watchdog-script' stderr output:
torr  | Unhandled error in Deferred:
torr  | 
torr  | 2022-08-06 18:48:26,379 DEBG 'watchdog-script' stderr output:
torr  | 
torr  | Traceback (most recent call last):
torr  |   File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
torr  |     current.result = callback(  # type: ignore[misc]
torr  |   File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 1338, in _cbDeferred
torr  |     self.callback(cast(_DeferredListResultListT, self.resultList))
torr  |   File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 662, in callback
torr  |     self._startRunCallbacks(result)
torr  |   File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 764, in _startRunCallbacks
torr  |     self._runCallbacks()
torr  | --- <exception caught here> ---
torr  |   File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
torr  |     current.result = callback(  # type: ignore[misc]
torr  |   File "/usr/lib/python3.10/site-packages/deluge/ui/web/json_api.py", line 190, in _on_rpc_request_failed
torr  |     return self._send_response(request, response)
torr  |   File "/usr/lib/python3.10/site-packages/deluge/ui/web/json_api.py", line 232, in _send_response
torr  |     response = json.dumps(response)
torr  |   File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
torr  |     return _default_encoder.encode(obj)
torr  |   File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
torr  |     chunks = self.iterencode(o, _one_shot=True)
torr  |   File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
torr  |     return _iterencode(o, 0)
torr  |   File "/usr/lib/python3.10/json/encoder.py", line 179, in default
torr  |     raise TypeError(f'Object of type {o.__class__.__name__} '
torr  | builtins.TypeError: Object of type Failure is not JSON serializable
torr  | 
torr  | 
torr  | 2022-08-06 18:48:26,379 DEBG 'watchdog-script' stderr output:
torr  | Unhandled error in Deferred:
torr  | 
torr  | 2022-08-06 18:48:26,380 DEBG 'watchdog-script' stderr output:
torr  | 
torr  | Traceback (most recent call last):
torr  | Failure: deluge.error.NotAuthorizedError: Auth level too low: 0 < 5`

**Comment by nabeelshaikh7** [comment]
I tried it and it still doesn't work

torr  | 2022-08-06 18:48:26,378 DEBG 'watchdog-script' stderr output:` 
torr  | Unhandled error in Deferred:
torr  | 
torr  | 2022-08-06 18:48:26,379 DEBG 'watchdog-script' stderr output:
torr  | 
torr  | Traceback (most recent call last):
torr  |   File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
torr  |     current.result = callback(  # type: ignore[misc]
torr  |   File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 1338, in _cbDeferred
torr  |     self.callback(cast(_DeferredListResultListT, self.resultList))
torr  |   File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 662, in callback
torr  |     self._startRunCallbacks(result)
torr  |   File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 764, in _startRunCallbacks
torr  |     self._runCallbacks()
torr  | --- <exception caught here> ---
torr  |   File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
torr  |     current.result = callback(  # type: ignore[misc]
torr  |   File "/usr/lib/python3.10/site-packages/deluge/ui/web/json_api.py", line 190, in _on_rpc_request_failed
torr  |     return self._send_response(request, response)
torr  |   File "/usr/lib/python3.10/site-packages/deluge/ui/web/json_api.py", line 232, in _send_response
torr  |     response = json.dumps(response)
torr  |   File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
torr  |     return _default_encoder.encode(obj)
torr  |   File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
torr  |     chunks = self.iterencode(o, _one_shot=True)
torr  |   File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
torr  |     return _iterencode(o, 0)
torr  |   File "/usr/lib/python3.10/json/encoder.py", line 179, in default
torr  |     raise TypeError(f'Object of type {o.__class__.__name__} '
torr  | builtins.TypeError: Object of type Failure is not JSON serializable
torr  | 
torr  | 
torr  | 2022-08-06 18:48:26,379 DEBG 'watchdog-script' stderr output:
torr  | Unhandled error in Deferred:
torr  | 
torr  | 2022-08-06 18:48:26,380 DEBG 'watchdog-script' stderr output:
torr  | 
torr  | Traceback (most recent call last):
torr  | Failure: deluge.error.NotAuthorizedError: Auth level too low: 0 < 5

**Comment by everettmorgan** [comment]
You need to edit the connection and input the password for the `localclient` account. You can find it in `/config/auth`.

<img width="671" alt="Screenshot 2024-07-27 at 9 02 27 PM" src="https://github.com/user-attachments/assets/af6c8f07-2aaf-412b-b17a-9c680e118471">

1. Login using the `deluge` password
2. Edit the connection
3. Input the password from `/config/auth`
4. Connect!

**Comment by jessielw** [comment]
> `localclient`

This works but this is craaazy lol
