### ISSUE TITLE
Web UI becomes unavailable when having multiple deluge containers with NordVPN

### ISSUE THREAD

**Issue by wranglatang** [binhex/arch-delugevpn#344]
Hello, I have two instances of Deluge with OpenVPN configured to connect to my Nord VPN. It seems that after a few minutes of the second container starts running, it fails and i get an error in Deluge web UI saying its unavailable and my  *arr services are unable to connect to it.

I have done some reading and it seems that Nord VPN wont allow multiple connections to the same server from two different devices on the same protocol. so for this I set my second container up to use a different server hoping to solve this issue but it still persists. Any suggestions? I cant see any unusual in the logs.
]

**Comment by wranglatang** [comment]
Okay looks like its happening even with just one docker running:
```
2022-12-26 20:43:20,382 DEBG 'watchdog-script' stdout output:
[info] Attempting to start Privoxy...

2022-12-26 20:43:21,514 DEBG 'watchdog-script' stdout output:
[info] Privoxy process started
[info] Waiting for Privoxy process to start listening on port 8118...

2022-12-26 20:43:21,539 DEBG 'watchdog-script' stdout output:
[info] Privoxy process listening on port 8118

2022-12-26 20:45:01,979 DEBG 'watchdog-script' stderr output:
Unhandled error in Deferred:

2022-12-26 20:45:01,979 DEBG 'watchdog-script' stderr output:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/usr/lib/python3.10/site-packages/twisted/internet/base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
  File "/usr/lib/python3.10/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python3.10/site-packages/twisted/internet/task.py", line 251, in __call__
    d = maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 205, in maybeDeferred
    result = f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/deluge/core/alertmanager.py", line 60, in update
    self.handle_alerts()
  File "/usr/lib/python3.10/site-packages/deluge/core/alertmanager.py", line 128, in handle_alerts
    **{
  File "/usr/lib/python3.10/site-packages/deluge/core/alertmanager.py", line 129, in <dictcomp>
    attr: getattr(alert, attr)
builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 0: invalid continuation byte
```

**Comment by aronjanosch** [comment]
I have the same problem
