### ISSUE TITLE
Unable to connect *arr apps

### ISSUE THREAD

**Issue by sameep22** [binhex/arch-delugevpn#376]
Hi,

I did try to look at all the other posts and issues. Tried a google search. Seems like a few people have had a similar issue, but none of their solutions worked for me. Please do redirect me to the right place, if this is a repeat. 

I have been trying to setup up Deluge (to replace Transmission) as my main download client. 

I managed to get the docker image up and running, I am able to connect to the WebUI as well. Yet, when I try to add it to any of the *arr apps, I get connection failed/timed out. 

This is my config in sonarr, but it is the same across the rest of the applications.

![image](https://github.com/binhex/arch-delugevpn/assets/40769516/6ccfc156-75f4-4fd6-832f-700058b2b966)

The password is correct. Here are the logs that I can see. 

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in ./Sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in ./Sonarr.Common/Http/HttpClient.cs:line 141
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 59
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.AuthenticateClient(JsonRpcRequestBuilder requestBuilder, DelugeSettings settings, Boolean reauthenticate) in ./Sonarr.Core/Download/Clients/Deluge/DelugeProxy.cs:line 307
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.BuildRequest(DelugeSettings settings) in ./Sonarr.Core/Download/Clients/Deluge/DelugeProxy.cs:line 214
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult](DelugeSettings settings, String method, Object[] arguments) in ./Sonarr.Core/Download/Clients/Deluge/DelugeProxy.cs:line 221
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.GetVersion(DelugeSettings settings) in ./Sonarr.Core/Download/Clients/Deluge/DelugeProxy.cs:line 54
   at NzbDrone.Core.Download.Clients.Deluge.Deluge.TestConnection() in ./Sonarr.Core/Download/Clients/Deluge/Deluge.cs:line 245
```

Please do let me know if there is any other information I can provide to help solve this. 

Thanks!!

**Comment by Paillat-dev** [comment]
May I see your docker compose / docker run for both the arr and deluge-vpn?

**Comment by Yodie98** [comment]
Im having this exact issue. Its probably user error, im on unraid
