### ISSUE TITLE
Permission error on extracting plugin (Scheduler-0.3-py2.7.egg)

### ISSUE THREAD

**Issue by michaelgoodwin** [binhex/arch-delugevpn#59]
Receiving this permission error when trying to enable the scheduler. This is on a clean install.
```
2018-05-04 11:43:34,651 DEBG 'deluge-web-script' stderr output:
[ERROR   ] 11:43:32 pluginmanagerbase:146 Unable to instantiate plugin!
[ERROR   ] 11:43:32 pluginmanagerbase:147 Can't extract file(s) to egg cache
The following error occurred while trying to extract file(s)
to the Python egg cache:
  [Errno 13] Permission denied: '/home/nobody/.cache/Python-Eggs/Scheduler-0.3-py2.7.egg-tmp'
The Python egg cache directory is currently set to:
  /home/nobody/.cache/Python-Eggs
Perhaps your account does not have write access to this directory?
You can change the cache directory by setting the PYTHON_EGG_CACHE
environment variable to point to an accessible directory.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/deluge/pluginmanagerbase.py", line 144, in enable_plugin
    instance = cls(plugin_name.replace("-", "_"))
  File "/usr/lib/python2.7/site-packages/deluge/plugins/Scheduler-0.3-py2.7.egg/scheduler/__init__.py", line 55, in __init__
    from webui import WebUI as _plugin_cls
  File "/usr/lib/python2.7/site-packages/deluge/plugins/Scheduler-0.3-py2.7.egg/scheduler/webui.py", line 46, in <module>
  File "/usr/lib/python2.7/site-packages/deluge/plugins/Scheduler-0.3-py2.7.egg/scheduler/webui.py", line 48, in WebUI
  File "/usr/lib/python2.7/site-packages/deluge/plugins/Scheduler-0.3-py2.7.egg/scheduler/common.py", line 41, in get_resource
    return pkg_resources.resource_filename("scheduler", os.path.join("data", filename))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1137, in resource_filename
    self, resource_name
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1646, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1675, in _extract_resource
    self.egg_name, self._parts(zip_path)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1204, in get_cache_path
    self.extraction_error()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1184, in extraction_error
    raise err
ExtractionError: Can't extract file(s) to egg cache
The following error occurred while trying to extract file(s)
to the Python egg cache:
  [Errno 13] Permission denied: '/home/nobody/.cache/Python-Eggs/Scheduler-0.3-py2.7.egg-tmp'
The Python egg cache directory is currently set to:
  /home/nobody/.cache/Python-Eggs
Perhaps your account does not have write access to this directory?
You can change the cache directory by setting the PYTHON_EGG_CACHE
environment variable to point to an accessible directory.
```

**Comment by michaelgoodwin** [comment]
I cannot figure out why I cant write into this directory as "nobody".

I'm able to write in the following directories with the same permissions.
/home/nobody/
/home/nobody/.cache/
```
[nobody@627248ec558e Python-Eggs]$ id
uid=1026(nobody) gid=101(users) groups=101(users),65534(nobody)

[nobody@627248ec558e Python-Eggs]$ getfacl $(pwd)
getfacl: Removing leading '/' from absolute path names
# file: home/nobody/.cache/Python-Eggs
# owner: nobody
# group: users
user::rwx
group::r-x
other::r-x

[nobody@627248ec558e Python-Eggs]$ touch test
touch: cannot touch 'test': Permission denied
```

**Comment by binhex** [comment]
im not sure whats going on with your configuration but writing to the Python-Eggs folder works perfectly fine in testing as shown below:-

```
docker exec -it --user nobody binhex-delugevpn /bin/bash
[nobody@6fb9b7b1228b /]$ whoami
nobody
[nobody@6fb9b7b1228b /]$ cd /home/nobody/.cache/
[nobody@6fb9b7b1228b .cache]$ ls -al
total 0
drwxrwxr-x 1 nobody users  22 Apr 12 14:12 .
drwxrwxr-x 1 nobody users 276 May 15 12:43 ..
drwxrwxr-x 1 nobody users   0 Apr 12 14:12 Python-Eggs
[nobody@6fb9b7b1228b .cache]$ cd Python-Eggs/
[nobody@6fb9b7b1228b Python-Eggs]$ ls -al
total 0
drwxrwxr-x 1 nobody users  0 Apr 12 14:12 .
drwxrwxr-x 1 nobody users 22 Apr 12 14:12 ..
[nobody@6fb9b7b1228b Python-Eggs]$ pwd
/home/nobody/.cache/Python-Eggs
[nobody@6fb9b7b1228b Python-Eggs]$ touch test
[nobody@6fb9b7b1228b Python-Eggs]$ ls -al
total 0
drwxrwxr-x 1 nobody users  8 May 15 12:44 .
drwxrwxr-x 1 nobody users 22 Apr 12 14:12 ..
-rw-r--r-- 1 nobody users  0 May 15 12:44 test
[nobody@6fb9b7b1228b Python-Eggs]$ echo "hello" > ./test 
[nobody@6fb9b7b1228b Python-Eggs]$ cat ./test 
hello
```

maybe your PUID and PGID values arent valid?

**Comment by michaelgoodwin** [comment]
Thanks for confirming it's something on my end.

So I did some more digging at the problem and found something that shouldn't work but did.

- Deleted the Python-Eggs folder.
- Created a new Python-Eggs folder.
- Write test file and make an edit.

With what I briefly know about docker it should return to the image state and stop me from writing again when I stop and start.

```
docker exec -it --user nobody binhex-arch-delugevpn /bin/bash
[nobody@002a02d75489 /]$ cd /home/nobody/.cache/Python-Eggs/
[nobody@002a02d75489 Python-Eggs]$ ls
Label-0.2-py2.7.egg-tmp  test
[nobody@002a02d75489 Python-Eggs]$ exit
docker stop binhex-arch-delugevpn
binhex-arch-delugevpn
docker start binhex-arch-delugevpn
binhex-arch-delugevpn
docker exec -it --user nobody binhex-arch-delugevpn /bin/bash
[nobody@002a02d75489 /]$ cd /home/nobody/.cache/Python-Eggs/
[nobody@002a02d75489 Python-Eggs]$ ls
Label-0.2-py2.7.egg-tmp  test
```

Not only do I still have write, but the test file is still there after committing a stop. ¯\\\_(ツ)\_/¯

----

Did more reading through Docker docs, found out about writable layers which I believe is what's happening here, but even they say it doesn't persist after a stop.

> Storage drivers allow you to create data in the writable layer of your container. The files won’t be persisted after the container stops, and both read and write speeds are low.
https://docs.docker.com/storage/storagedriver/

I don't know what to think of docker now. 🙃
